### ISSUE TITLE
Multi GPU

### ISSUE THREAD

**Issue by Denisevi4** [rapidsai/pygdf#279]
If I'm creating multiple GPU dataframes. Is there a way to distribute them to different devices?

**Comment by scopatz** [comment]
I believe that this is what dask_gdf is for, @Denisevi4

**Comment by Denisevi4** [comment]
Thanks. It seems dask_gdf distributes each dataframe. It has its own interface that appears not compatible with what I'm doing. 

For now I'm interested in say putting entire GPU dataframe into a GPU with a given gpu_id. Right now everything is going to gpu_id=0

**Comment by kkraus14** [comment]
@Denisevi4 You can use dask_gdf for doing that, but you should start each worker with a different GPU mapped to gpu 0. I.E. if you wanted to use two GPUs you could start the dask workers as follows:

```
CUDA_VISIBLE_DEVICES=0,1 dask-worker --nprocs=1 --nthreads=1
CUDA_VISIBLE_DEVICES=1,0 dask-worker --nprocs=1 --nthreads=1
```

We expose the additional devices to allow for cross-GPU communication using CUDA IPC and use 1 thread and 1 process per worker to avoid multiple tasks from executing on a single GPU at once.
